---
name: GCC Conan

# This workflow is triggered on pushes to the repository.
on: [push, workflow_dispatch]

env:
  SINTEF_REFERENCE: "opensplice-ce*"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: true
  CONAN_USE_ALWAYS_SHORT_PATHS: true

jobs:
  conan-with-gcc:
    name: Conan
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler_version: [63, 7, 8, 9, 10]
        build_type: [Debug, Release]
        os: [ubuntu-20.04]
    container:
      image: conanio/gcc${{ matrix.compiler_version }}
      options: -u 0
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo pip3 install --upgrade setuptools pip cython wheel
          sudo pip3 install conan --upgrade
          sudo apt-get install -y bison flex gawk
          sudo apt-get remove -y '*jdk*'
      - name: Configure Conan
        run: conan remote add sintef ${CONAN_UPLOAD} --insert 0
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -s arch_build=x86_64 \
            -s os_build=Linux \
            -s compiler.libcxx=libstdc++11 \
            -b missing -b outdated . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
