name: Android Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_REFERENCE: "opensplice-ce*"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: True
  CONAN_USE_ALWAYS_SHORT_PATHS: True

jobs:
  conan-with-android:
    name: Conan
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, armv8]
        api_level: [28]
        build_type: [Release]
    container:
      image: conanio/gcc8
      options: -u 0
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo pip3 install --upgrade setuptools pip cython wheel requests
          sudo pip3 install --upgrade conan
          sudo apt-get install -y bison flex gawk
          sudo apt-get remove -y '*jdk*'
      - name: Configure Conan
        run: |
          conan remote add sintef ${CONAN_UPLOAD} --insert 0
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan config set general.revisions_enabled=1
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -s os=Android \
            -s os_build=Linux \
            -s os.api_level=${{ matrix.api_level }} \
            -s arch=${{ matrix.arch }} \
            -s arch_build=x86_64 \
            -s compiler=clang \
            -s compiler.version=9 \
            -s compiler.libcxx=c++_shared \
            -b missing -b outdated -b android_ndk_installer \
            . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
