---
name: Clang Conan

# This workflow is triggered on pushes to the repository.
on: [push, workflow_dispatch]

env:
  SINTEF_REFERENCE: "opensplice-ce*"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: true
  CONAN_USE_ALWAYS_SHORT_PATHS: true

jobs:
  conan-with-clang:
    name: Conan
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler_version: [9]
        build_type: [Debug, Release]
        os: [ubuntu-20.04]
    container:
      image: debian:bullseye
    env:
      CC: clang-${{ matrix.compiler_version }}
      CXX: clang++-${{ matrix.compiler_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          echo Compiler: $CXX
          apt-get update
          apt-get install -y bison flex gawk make \
            clang-tools-${{ matrix.compiler_version }} git cmake python3-pip
          pip3 install --upgrade setuptools pip cython wheel conan requests
          ln -s /usr/bin/clang-${{ matrix.compiler_version }} /usr/bin/clang
          ln -s /usr/bin/clang++-${{ matrix.compiler_version }} /usr/bin/clang++
          apt-get remove -y '*jdk*'
      - name: Configure Conan
        run: conan remote add sintef ${CONAN_UPLOAD} --insert 0
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler=clang \
            -s compiler.libcxx=libstdc++11 \
            -b missing -b outdated . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
