name: MSVC 2022 Conan

# This workflow is triggered on pushes to the repository.
on: [push]

env:
  SINTEF_REFERENCE: "opensplice-ce*"
  SINTEF_LIBNAME: "opensplice-ce"
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONAN_NON_INTERACTIVE: True
  SINTEF_REMOTE: sintef

jobs:
  conan-with-msvc:
    name: Conan
    runs-on: ${{ matrix.os }}
    env:
      CONAN_USER_HOME_SHORT: C:\c
      CONAN_USE_ALWAYS_SHORT_PATHS: 1
      CONAN_BASH_PATH: C:\tools\cygwin\bin\bash.exe
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        build_type: [Debug, Release]
        option_include_cs: [include_cs=True, include_cs=False]
        compiler_version: [17]
        compiler_toolset: [v143]

    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip cython wheel requests
          pip3 install --upgrade conan
          choco install cygwin
          choco install cyg-get
          cyg-get gcc-core make git perl bison flex gawk zip unzip dos2unix
      - name: Configure Conan
        run: conan remote add sintef ${env:CONAN_UPLOAD} --insert 0
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} `
            -s compiler.toolset=${{ matrix.compiler_toolset }} `
            -s compiler.version=${{ matrix.compiler_version }} `
            -s compiler="Visual Studio" `
            -o ${env:SINTEF_LIBNAME}:${{matrix.option_include_cs}} `
            -b missing -b outdated . sintef/stable
      - name: Conan upload
        run: |
          conan upload --all -c -r sintef ${env:SINTEF_REFERENCE} --retry 10 --retry-wait 20 --force
